### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by michael-azogu** [secureterminal/100-Days-of-Code#1]
from random import choice

word = choice(["bat", "door", "freedom", "star"])

dashes = "_" * len(word)

while True:
  selection = input("Choose a letter: ")[0].lower()
  
  matches = []
  idx = 0
  
  for letter in word:
    if letter == selection:
      matches.append(idx)
    idx += 1
    
  for i in matches:
    temp = " ".join(dashes).split(" ")
    temp[i] = selection
    dashes = ''.join(temp)

  print(" ".join(dashes))
  
  if dashes == word:
    break

**Comment by secureterminal** [comment]
I like this, this is another angle to analyse this problem. It is a shorter way to solve it. Thanks
